plugins {
	id 'net.neoforged.moddev' version '2.0.96'
	id 'maven-publish'
}

version = mod_version
group = mod_group_id

repositories {
	maven { url "https://maven.neoforged.net" }
	maven { url "https://maven.parchmentmc.org" }

	// EMI
	maven {
		url "https://maven.terraformersmc.com/releases/"
		content {
			includeGroup("dev.emi")
			includeGroup("com.terraformersmc")
		}
	}

	// REI
	maven {
		url "https://maven.shedaniel.me/"
		content {
			includeGroup("me.shedaniel")
			includeGroup("me.shedaniel.cloth")
			includeGroup("me.shedaniel.cloth.api")
			includeGroup("dev.architectury")
		}
	}

	// JEI
	maven {
		url "https://maven.blamejared.com/"
		content {
			includeGroup("mezz.jei")
		}
	}
}

base {
	archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')
//minecraft.accessTransformers.entry public net.minecraft.client.Minecraft textureManager # textureManager

// Default run configurations.
// These can be tweaked, removed, or duplicated as needed.

dependencies {
	// Recipe viewers
	compileOnly("mezz.jei:jei-${project.minecraft_version}-neoforge-api:${project.jei_version}")
	compileOnly("me.shedaniel:RoughlyEnoughItems-api-neoforge:${project.rei_version}")
	compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${project.rei_version}")
	compileOnly("dev.emi:emi-neoforge:${project.emi_version}")
	compileOnly("dev.emi:emi-neoforge:${project.emi_version}:api")

	/*switch(project.recipe_viewer) {
		case "jei": runtimeOnly("mezz.jei:jei-${project.minecraft_version}-neoforge:${project.jei_version}")
		case "rei" -> runtimeOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}")
		case "emi" -> runtimeOnly("dev.emi:emi-neoforge:${project.emi_version}")
		case "disabled" -> {}
		default -> println("Unknown recipe viewer specified: ${project.recipe_viewer}. Must be EMI, REI or disabled.")
	}*/
}

neoForge {
	version = project.neoforge_version

	addModdingDependenciesTo(sourceSets.test)

	parchment {
		minecraftVersion = project.parchment_minecraft_version
		mappingsVersion = project.parchment_mappings_version
	}

	interfaceInjectionData = files("interfaces.json")

	interfaceInjectionData {
		publish file("interfaces.json")
	} // ???

	accessTransformers {
		file('src/main/resources/META-INF/accesstransformer.cfg')
	}

	// Default run configurations.
	// These can be tweaked, removed, or duplicated as needed.
	runs {
		client {
			client()
		}

		testmodClient {
			client()
			sourceSet = sourceSets.test
		}

		server {
			server()
			programArgument '--nogui'
		}

		// applies to all the run configs above
		configureEach {
			// Recommended logging data for a userdev environment
			// The markers can be added/remove as needed separated by commas.
			// "SCAN": For mods scan.
			// "REGISTRIES": For firing of registry events.
			// "REGISTRYDUMP": For getting the contents of all registries.
			systemProperty 'forge.logging.markers', 'REGISTRIES'

			// Recommended logging level for the console
			// You can set various levels here.
			// Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		fractal {
			sourceSet sourceSets.main
		}
		fractal_test {
			sourceSet sourceSets.main
			sourceSet sourceSets.test
		}
	}
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}" }
	}
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
	var replaceProperties = [
			minecraft_version      : minecraft_version,
			minecraft_version_range: minecraft_version_range,
			neoforge_version       : neoforge_version,
			neoforge_version_range : neoforge_version_range,
			loader_version_range   : loader_version_range,
			mod_id                 : mod_id,
			mod_name               : mod_name,
			mod_license            : mod_license,
			mod_version            : mod_version,
			mod_authors            : mod_authors,
			mod_description        : mod_description
	]
	inputs.properties replaceProperties
	expand replaceProperties
	from "src/main/templates"
	into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
	it.options.release = 21 // Minecraft 1.20.5 upwards uses Java 21.
}

// configure the maven publication
publishing {
	publications {
		register('mavenJava', MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		maven {
			name = "sapphoCompany"
			url = "https://maven.is-immensely.gay/releases"
			credentials {
				username = "dafuqs"
				password = System.getenv("MAVEN_PASS")
			}
		}
	}
}
