# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Minecraft
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)

# Parchment Mappings https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

# https://neoforged.net/
neoforge_version=21.11.13-beta
neoforge_version_range=[21.11.13-beta,)
loader_version_range=[4,)

# Mod Properties
mod_id=fractal
mod_name=Fractal
archives_base_name=fractal-neoforge
mod_license=MIT
mod_version=2.0.0+1.21.11-neoforge
mod_group_id=de.dafuqs
mod_authors=Unascribed, DaFuqs, EmmaTheMartian
mod_description=Subtabs for the creative menu

## Dependency Versions
jei_version=27.3.0.10
rei_version=21.9.812
emi_version=1.1.22+1.21.1

# Which recipe viewer to use ('jei', 'rei', 'emi', or 'disabled')
recipe_viewer=disabled